export const Elementos = {
    paginaColaborador: 'https://localhost:7294/Collaborator',
    nome: '[name="Name"]',
    dataNascimento: '[name="BirthDate"]',
    rg: '[name="RG"]',
    email: '[name=Email]',
    observacao:'[name=Observation]',
    ferramentasSoftware: '[data-bs-target="#collapseTwo"]',
    frameworks: '[data-bs-target="#collapseThree"]',
    infraestrutura: '[data-bs-target="#collapseFour"]',
    linguagemProgramacao: '[data-bs-target="#collapseFive"]',
    metodologia: '[data-bs-target="#collapseSix"]',
    gravar: '.btn-secondary',
    novoColaborador: '[href="/Collaborator/Create"]',
    checkbox: '[type="checkbox"]',
    verificar: '.page-title-3',
    editarId: '[href="/Collaborator/Edit/35"]',
    deletarId: '[href="/Collaborator/Delete/21"]',
    mensagem: '.alert',
    editar: '[title="Editar"]',
    deletar: '[title="Apagar"]'
}